### ISSUE TITLE
install.sh script terminates with an error - provision_node.sh not found

### ISSUE THREAD

**Issue by rhastie** [bbc/nmos-web-router#24]
The install.sh script errors as it can't access the provision_node.sh script...

> Reading state information... Done
> nodejs is already the newest version (8.16.2-1nodesource1).
> yarn is already the newest version (1.19.1-1).
> The following packages were automatically installed and are no longer required:
>   linux-headers-4.15.0-64 linux-headers-4.15.0-64-generic linux-image-4.15.0-64-generic linux-modules-4.15.0-64-generic
>   linux-modules-extra-4.15.0-64-generic
> Use 'sudo apt autoremove' to remove them.
> 0 to upgrade, 0 to newly install, 0 to remove and 171 not to upgrade.
> mkdir: cannot create directory ‘/home/vagrant’: File exists
> ./provision_node.sh: line 1: 404:: command not found
> rhastie@ubuntu:~/nmos/nmos-web-router$

It looks like the git path used in the install.sh script points to a git repo that no longer has the script available

**Comment by andrewbonney** [comment]
Looks like it's become a bit out of sync with our approach to provisioning the other repo. I've pushed up a quick fix which should get things unstuck for now.

**Comment by rhastie** [comment]
This looks resolved... Thanks
